import React from "react";

const TheGym = () => {
  // Room: Strength Room
  const strengthImageUrls = [
    "DSC08823.jpg",
    "DSC08824.jpg",
    "DSC08825.jpg",
    "DSC08828.jpg",
    "DSC08829.jpg",
    "DSC08830.jpg",
  ];

  const strengthImagesFolder = "/images/strength-room/";

  // Room: Cardio & Abs
  const cardioAndAbsImageUrls = [
    "DSC08815.jpg",
    "DSC08816.jpg",
    "DSC08817.jpg",
    "DSC08818.jpg",
    "DSC08821.jpg",
    "DSC08822.jpg",
  ];

  const cardioAndAbsImagesFolder = "/images/cardio-and-abs-room/";

  // Room: Chest & Back Room
  const chestAndBackImageUrls = [
    "DSC08832.jpg",
    "DSC08833.jpg",
    "DSC08834.jpg",
    "DSC08837.jpg",
    "DSC08839.jpg",
    "DSC08840.jpg",
  ];

  const chestAndBackImagesFolder = "/images/chest=and-back-room/";

  // Room: Shoulders & Arms Room
  const shouldersAndArmsImageUrls = [
    "DSC08841.jpg",
    "DSC08842.jpg",
    "DSC08843.jpg",
    "DSC08844.jpg",
    "DSC08846.jpg",
  ];

  const shouldersAndArmsImagesFolder = "/images/shoulders-and-arms-room/";

  // Room: HIIT Room
  const hiitImageUrls = [
    "DSC08849.jpg",
    "DSC08851.jpg",
    "DSC08853.jpg",
    "DSC08854.jpg",
    "DSC08855.jpg",
    "DSC08856.jpg",
    "DSC08857.jpg",
    "DSC08858.jpg",
    "DSC08859.jpg",
  ];

  const hiitImagesFolder = "/images/hiit-room/";

  // Room: Leg Room
  const legImageUrls = [
    "DSC08862.jpg",
    "DSC08863.jpg",
    "DSC08864.jpg",
    "DSC08865.jpg",
    "DSC08866.jpg",
    "DSC08867.jpg",
    "DSC08868.jpg",
    "DSC08869.jpg",
    "DSC08870.jpg",
  ];

  const legImagesFolder = "/images/leg-room/";

  // Room: Boxing & Bikes Room
  const boxingAndBikesImageUrls = [
    "DSC08871.jpg",
    "DSC08872.jpg",
    "DSC08873.jpg",
    "DSC08874.jpg",
  ];

  const boxingAndBikesImagesFolder = "/images/boxing-and-bikes-room/";

  // Create an array of all rooms
  const rooms = [
    {
      name: "STRENGTH ROOM",
      imageUrls: strengthImageUrls,
      imagesFolder: strengthImagesFolder,
      text: "FIRST UP IS OUR STRENGTH ROOM, WHICH IS ENTIRELY DEDICATED TO STRENGTH TRAINING FEATURING A NUMBER OF POWER RACKS, DEADLIFT PLATFORMS AND A HOST OF OTHER EQUIPMENT THAT WILL HELP YOU IMPROVE YOUR STRENGTH AND POWER FOR ANY SPORT. THE STRENGTH ROOM ALSO INCLUDES COMPETITION BENCHES, RESISTANCE BANDS, PLYOMETRIC BOXES AND JUST ABOUT EVERY VARIATION OF BARBELL YOU CAN THINK OF. ADD TO THIS CALIBRATED ELEIKO PLATES AND THIS MAKES IT THE PERFECT ROOM TO INCREASE STRENGTH, POWER AND PERFORMANCE.",
    },

    {
      name: "CARDIO & ABS ROOM",
      imageUrls: cardioAndAbsImageUrls,
      imagesFolder: cardioAndAbsImagesFolder,
      text: `WELCOME TO OUR STATE-OF-THE-ART CARDIO AND ABS ROOM AT PACIFIC FITNESS! THIS ULTIMATE HAVEN FOR FITNESS ENTHUSIASTS ELEVATES YOUR CARDIOVASCULAR TRAINING AND HELPS YOU ACHIEVE YOUR HEALTH GOALS. STEP INTO A WORLD OF CUTTING-EDGE FITNESS EQUIPMENT AND GET A GREAT WORKOUT EVERY TIME.
      
        AT PACIFIC FITNESS, WE VALUE THE IMPORTANCE OF CARDIOVASCULAR EXERCISE FOR OVERALL FITNESS AND WELL-BEING. THAT’S WHY WE’VE SPARED NO EXPENSE IN CURATING A TOP-NOTCH SELECTION OF CARDIO EQUIPMENT, Catering to ALL FITNESS LEVELS AND PREFERENCES.
      
        READY TO ELEVATE YOUR CARDIO SESSIONS? OUR CARDIO ROOM OFFERS AN IMPRESSIVE LINEUP OF PREMIUM EQUIPMENT, INCLUDING EVER-POPULAR STAIRMASTERS AND HIGH-INTENSITY STEPPERS THAT CHALLENGE WHILE BEING GENTLE ON YOUR JOINTS. ENGAGE MULTIPLE MUSCLE GROUPS WITH OUR CROSS-TRAINERS, PROVIDING A FANTASTIC FULL-BODY WORKOUT THAT LEAVES YOU INVIGORATED AND ACCOMPLISHED.
      
        DISCOVER THE NEXT LEVEL OF CARDIO TRAINING WITH OUR CUTTING-EDGE INTERVAL RUNNERS. CUSTOMIZE YOUR WORKOUT WITH VARYING INTENSITIES TO PUSH BOUNDARIES AND MAXIMIZE CALORIE BURN. WHETHER YOU’RE A SEASONED ATHLETE OR JUST STARTING YOUR FITNESS JOURNEY, THESE INTERVAL RUNNERS WILL HELP YOU ACHIEVE YOUR DESIRED RESULTS MORE EFFICIENTLY.
      
        AND THAT’S NOT ALL! OUR CARDIO AND ABS ROOM ALSO FEATURES SPECIALIZED AB MACHINES DESIGNED TO TARGET EVERY ANGLE OF YOUR ABDOMINAL MUSCLES. STRENGTHEN YOUR CORE AND ACHIEVE A SCULPTED MIDSECTION WITH OUR RANGE OF EQUIPMENT.`,
    },

    {
      name: "CHEST & BACK ROOM",
      imageUrls: chestAndBackImageUrls,
      imagesFolder: chestAndBackImagesFolder,
      text: `NEXT UP IS THE CHEST AND BACK ROOM. AT PACIFIC FITNESS, WE BELIEVE IN PROVIDING OUR MEMBERS WITH NOTHING BUT THE BEST, AND THIS ROOM IS A TESTAMENT TO THAT COMMITMENT. OUR OWNER, ALI, HAS HANDPICKED EACH PIECE OF EQUIPMENT WITH UTMOST CARE AND PRECISION TO ENSURE YOU HAVE ACCESS TO CUTTING-EDGE TOOLS TO MAXIMISE YOUR TRAINING EXPERIENCE.

      FIRST, LET’S TALK ABOUT CHEST TRAINING. OUR ROOM BOASTS AN IMPRESSIVE ARRAY OF STATE-OF-THE-ART MACHINES AND FREE WEIGHTS, ALLOWING YOU TO CHALLENGE YOUR CHEST MUSCLES FROM EVERY CONCEIVABLE ANGLE. WHETHER YOU’RE LOOKING TO SCULPT A DEFINED CHEST, ENHANCE YOUR BENCH PRESS STRENGTH, OR INCREASE OVERALL UPPER BODY POWER, WE HAVE THE PERFECT EQUIPMENT FOR YOU. WE HAVE CUSTOM MADE, PACIFIC FITNESS BRANDED DUMBBELLS RANGING FROM 2.5 KG TO 50 KG AS WELL AS, SMITH MACHINES, INCLINE PRESS, DECLINE PRESS, FLAT PRESS AND FLY MACHINES.
      
      THE CENTREPIECE OF OUR CHEST AND BACK ROOM IS THE LEGENDARY NAUTILUS PULLOVER, A RARE GEM IN THE FITNESS WORLD. THERE ARE ONLY A HANDFUL OF THESE MACHINES LEFT IN THE ENTIRE WORLD, AND WE’RE THRILLED TO BE ONE OF THE FEW GYMS THAT HOUSES IT. THE NAUTILUS PULLOVER IS RENOWNED FOR ITS UNIQUE DESIGN, TARGETING THE CHEST, UPPER BACK, AND SHOULDERS SIMULTANEOUSLY, PROVIDING AN UNRIVALED TRAINING EXPERIENCE. YOU’LL BE ABLE TO ISOLATE AND WORK THOSE MUSCLES LIKE NEVER BEFORE, AND UNLOCK HIDDEN POTENTIAL.
      
      NOW, LET’S SHIFT OUR FOCUS TO THE BACK TRAINING SECTION. YOUR BACK MUSCLES PLAY A CRUCIAL ROLE IN SUPPORTING OVERALL STRENGTH AND POSTURE. TO OPTIMISE YOUR BACK WORKOUTS, WE HAVE CURATED AN EXTENSIVE COLLECTION OF CUTTING-EDGE EQUIPMENT THAT TARGETS EVERY ASPECT OF YOUR BACK MUSCLES. FROM ROWING MACHINES, LAT PULLDOWNS AND PULL-UP BARS TO CABLE STATIONS AND HYPEREXTENSION BENCHES, YOU’LL FIND AN EXTENSIVE ARRAY OF OPTIONS THAT CATER TO EVERY FITNESS LEVEL AND TRAINING PREFERENCE.`,
    },

    {
      name: "SHOULDERS & ARMS ROOM",
      imageUrls: shouldersAndArmsImageUrls,
      imagesFolder: shouldersAndArmsImagesFolder,
      text: `WELCOME OUR DEDICATED SHOULDERS AND ARMS ROOM. IN THIS ROOM YOU WILL FIND A COMPREHENSIVE RANGE OF EQUIPMENT DESIGNED TO TARGET YOUR SHOULDERS AND ARMS EFFECTIVELY, INCLUDING SEATED SHOULDER PRESS MACHINES, SIDE LATERAL MACHINES AND THE VIKING PRESS FOR SHOULDERS AS WELL AS PREACHER CURL MACHINES, ISOLATED BICEP EQUIPMENT AND ACCESSORIES FOR BICEP TRAINING.

      ADDITIONALLY, FOR THOSE WHO PREFER THE VERSATILITY AND CHALLENGE OF FREE WEIGHTS, WE HAVE PROVIDED AN ADDITIONAL SECOND SET OF DUMBBELLS RANGING FROM 2.5 KG TO 50 KG. THESE DUMBBELLS OFFER YOU THE FLEXIBILITY TO CUSTOMISE YOUR EXERCISES AND ADJUST THE INTENSITY OF YOUR WORKOUTS ACCORDING TO YOUR PREFERENCES AND FITNESS LEVEL.`,
    },

    {
      name: "HIIT ROOM",
      imageUrls: hiitImageUrls,
      imagesFolder: hiitImagesFolder,
      text: `UP NEXT IS OUR HIIT ROOM AT PACIFIC FITNESS, THE ULTIMATE DESTINATION FOR HIGH-INTENSITY TRAINING ENTHUSIASTS! AS YOU STEP INTO THIS DYNAMIC SPACE, YOU’LL BE GREETED BY A FULLY ASTROTURFED FLOOR, SETTING THE STAGE FOR AN ENERGETIC AND INVIGORATING WORKOUT.

      OUR HIIT ROOM BOASTS AN IMPRESSIVE COLLECTION OF STATE-OF-THE-ART EQUIPMENT, INCLUDING CONCEPT 2’S ROWING MACHINES, WATT BIKES FOR INTENSE CYCLING SESSIONS, SKIERG’S FOR A CHALLENGING FULL-BODY WORKOUT, AND ROUGE ASSAULT BIKES FOR A HEART-POUNDING CARDIO EXPERIENCE.
      
      THE HIIT ROOM IS DESIGNED TO CATER TO INDIVIDUALS WHO THRIVE ON PUSHING THEIR LIMITS AND EMBRACING THE INTENSITY OF THEIR WORKOUTS. WHETHER YOU’RE A SEASONED ATHLETE OR JUST BEGINNING YOUR FITNESS JOURNEY, OUR HIIT ROOM OFFERS A DIVERSE RANGE OF EQUIPMENT TO CATER TO ALL FITNESS LEVELS AND GOALS.
      
      CONCEPT 2’S ROWING MACHINES PROVIDE A FULL-BODY WORKOUT, ENGAGING YOUR LEGS, CORE, AND UPPER BODY IN A COORDINATED EFFORT TO BUILD STRENGTH AND ENDURANCE. THESE MACHINES ARE IDEAL FOR ANYONE LOOKING TO BOOST CARDIOVASCULAR FITNESS, IMPROVE MUSCULAR STRENGTH, AND BURN CALORIES EFFICIENTLY.
      
      FOR THOSE SEEKING THE ULTIMATE CYCLING EXPERIENCE, OUR WATT BIKES ARE A GAME-CHANGER. WITH PRECISE POWER MEASUREMENT AND PERFORMANCE TRACKING CAPABILITIES, YOU CAN MONITOR YOUR PROGRESS AND CHALLENGE YOURSELF TO REACH NEW HEIGHTS IN EVERY SESSION.
      
      LOOKING TO SCULPT A POWERFUL UPPER BODY AND CORE? THE SKIERG’S OFFER A UNIQUE AND EFFECTIVE WORKOUT THAT MIMICS THE MOVEMENTS OF CROSS-COUNTRY SKIING, ENGAGING YOUR ARMS, SHOULDERS, AND CORE MUSCLES IN A DYNAMIC MANNER.
      
      IF YOU’RE AFTER AN INTENSE CARDIO WORKOUT, OUR ROUGE ASSAULT BIKES ARE THE PERFECT CHOICE. WITH THEIR AIR RESISTANCE SYSTEM, YOU CONTROL THE INTENSITY BY PEDALING HARDER, MAKING THEM SUITABLE FOR BOTH BEGINNERS AND ADVANCED USERS.`,
    },

    {
      name: "LEG ROOM",
      imageUrls: legImageUrls,
      imagesFolder: legImagesFolder,
      text: `NOW, LET’S DIVE INTO OUR LEG ROOM – A STANDOUT FEATURE HERE AT PACIFIC FITNESS THAT WE’RE TRULY PROUD OF AND IN OUR OPINION, THE BEST LEG ROOM WALES HAS EVER HAD…

      TOP-NOTCH EQUIPMENT: GET READY TO EXPERIENCE THE LATEST IN LEG-TRAINING TECHNOLOGY WITH OUR WIDE SELECTION OF PREMIUM EQUIPMENT. WE’VE CAREFULLY CURATED A RANGE OF MACHINES FROM WELL-KNOWN BRANDS LIKE ATLANTIS, ROGERS ATHLETICS, PANATTA, AND CYBEX. THIS MEANS YOU’LL HAVE ACCESS TO TOP-QUALITY TOOLS THAT LET YOU TARGET EVERY LEG MUSCLE WITH PRECISION AND EFFICIENCY.
      
      SOMETHING FOR EVERYONE: NO MATTER WHERE YOU ARE IN YOUR FITNESS JOURNEY, THE LEG ROOM IS DESIGNED TO CATER TO ALL LEVELS OF EXPERIENCE. FROM BEGINNERS TO SEASONED ATHLETES, THERE’S A VARIETY OF LEG EXERCISES AVAILABLE. WHETHER YOU ENJOY CLASSIC MOVEMENTS OR PREFER MORE SPECIALISED OPTIONS, WE’VE GOT YOU COVERED.
      
      GUIDANCE FROM EXPERTS: OUR CERTIFIED TRAINERS ARE COMMITTED TO HELPING YOU SUCCEED. THEY’LL BE THERE TO PROVIDE PERSONALISED GUIDANCE, OFFER TIPS ON FORM AND TECHNIQUE, AND TAILOR TRAINING PROGRAMS THAT SUIT YOUR NEEDS. WITH THEIR EXPERTISE AND ENCOURAGEMENT, YOU’LL DISCOVER NEWFOUND STRENGTH AND EXCEED YOUR OWN EXPECTATIONS.`,
    },

    {
      name: "BOXING & BIKES ROOM",
      imageUrls: boxingAndBikesImageUrls,
      imagesFolder: boxingAndBikesImagesFolder,
      text: `LAST BUT CERTAINLY NOT LEAST IS OUR ACTION-PACKED BOXING AND BIKES ROOM! THIS ROOM IS EQUIPPED WITH AN ARRAY OF EQUIPMENT DESIGNED TO CATER TO YOUR BOXING AND CARDIO TRAINING NEEDS.

      LET’S START WITH THE ESSENTIALS FOR AN EMPOWERING BOXING EXPERIENCE. OUR HEAVY BAGS AND TOP-QUALITY BOXING GLOVES ARE READY TO HELP YOU UNLEASH YOUR INNER FIGHTER AND ENHANCE YOUR CARDIOVASCULAR ENDURANCE.
      
      IN ADDITION TO THE HEAVY BAGS AND GLOVES, WE HAVE THE POPULAR BOXMASTER, A VERSATILE BOXING TRAINING SYSTEM THAT CHALLENGES YOUR SPEED, ACCURACY, AND POWER. WHETHER YOU’RE A SEASONED BOXER OR NEW TO THE SPORT, THE BOXMASTER OFFERS AN ENGAGING AND EFFECTIVE WAY TO ELEVATE YOUR BOXING SKILLS.
      
      BUT THAT’S NOT ALL – WE’VE GOT YOU COVERED FOR YOUR CARDIO FIX AS WELL. OUR SPIN BIKES ARE GEARED UP AND READY TO TAKE YOU ON A THRILLING RIDE. PEDAL YOUR WAY TO BETTER CARDIOVASCULAR HEALTH, BURN CALORIES, AND BOOST YOUR ENDURANCE IN OUR EXHILARATING SPIN CLASSES.
      
      IN THE BOXING AND BIKES ROOM, WE BELIEVE IN THE POWER OF GROUP MOTIVATION. MANY OF OUR CLASSES ARE HELD IN THIS DYNAMIC SPACE, INCLUDING THE EVER-POPULAR SPIN CLASS. JOIN US FOR AN ENERGETIC AND SWEAT-INDUCING SESSION THAT GUARANTEES TO GET YOUR HEART PUMPING.`,
    },
  ];

  return (
    <>
      <section className="text-light">
        <h1 className="text-center">The Gym</h1>
      </section>

      <section className="text-light text-center">
        <div className="container">
          <h2 className="pt-4 pb-3">
            PACIFIC SUPERGYM - WALES' #1 TRAINING FACILITY
          </h2>
          <p className="lead">
            LOCATED IN TREFOREST INDUSTRIAL ESTATE, PACIFIC SUPERGYM HAS FAST
            BECOME ONE OF THE MOST POPULAR GYMS IN WALES. WITH INDUSTRY LEADING
            RESISTANCE EQUIPMENT FROM THE LIKES OF HAMMER STRENGTH, NAUTILUS,
            PANATTA AND HOIST JUST TO NAME A FEW, AS WELL AS CUTTING EDGE CARDIO
            EQUIPMENT FROM BRANDS SUCH AS CYBEX, LIFE FITNESS AND STAIR MASTER,
            YOU CAN BE CERTAIN THAT YOU WILL BE ABLE TO GET A GREAT WORKOUT IN
            EVERY TIME.
            <br />
            <br />
            THE GYM IS DIVIDED INTO A NUMBER OF ROOMS ACROSS TWO FLOORS, WITH
            EACH ROOM CATERING FOR A SPECIFIC FUNCTION OR BODY PART TO TRAIN.
            THIS ALLOWS YOU TO MAXIMISE YOUR TRAINING AND HIT EVERY BODY PART
            FROM EVERY ANGLE.
            <br />
          </p>
        </div>
      </section>

      {/* Dynamic Rooms */}
      {rooms.map((room, index) => (
        <section key={index}>
          <h2 className="pt-5 pb-3 text-light text-center">{room.name}</h2>
          <p className="pb-3 text-center text-light">{room.text}</p>
          <div className="container">
            <div className="row">
              {room.imageUrls.map((imageName, imageIndex) => (
                <div className="col-md-4" key={imageIndex}>
                  <img
                    className="img-fluid"
                    src={process.env.PUBLIC_URL + room.imagesFolder + imageName}
                    alt={`${room.name} Image ${imageIndex + 1}`}
                  />
                </div>
              ))}
            </div>
          </div>
        </section>
      ))}
    </>
  );
};

export default TheGym;
